version: "3.1"

services:
  server:
    build: .
    command: "python3 manage.py runserver 127.0.0.1:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/RockNBlockTestTask
    env_file:
      - RockNBlockTestTask/service_config
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1~
    ports:
      - "5432:5432"

volumes:
  postgres_data: