version: "3.1"

services:
  server:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    ports:
    - "8000:8000"
    - "5432:5432"
    -
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=posgtres
      - POSTGRES_DB=posgtres
      - POSTGRES_PASSWORD=1~