# Generated by Django 4.0.3 on 2022-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('unique_hash', models.BigIntegerField()),
                ('tx_hash', models.BigIntegerField()),
                ('media_url', models.URLField()),
                ('owner', models.CharField(max_length=42)),
            ],
        ),
    ]
