# Generated by Django 4.0.3 on 2022-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='media_url',
            field=models.URLField(db_column='media_url'),
        ),
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.CharField(db_column='owner', max_length=42),
        ),
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(blank=True, db_column='tx_hash', max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='unique_hash',
            field=models.CharField(db_column='unique_hash', max_length=20),
        ),
    ]
