# Generated by Django 4.0.3 on 2022-04-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_token_id_alter_token_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(blank=True, db_column='tx_hash', max_length=200),
        ),
    ]
